name: fc_default_theme
description: "Оформление по умолчанию и команды выбора темы."
publish_to: 'none'
version: 1.0.0

resolution: workspace

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  fc_api:
    path: ../api


  fc_ui_api:
    path: ../ui_api

  fc_ui_kit:
    path: ../ui_kit

dev_dependencies:
  flutter_test:
    sdk: flutter

  fc_test_kit:
    path: ../test_kit
