name: fc_file_icons
description: "Иконка строки по правилам: глиф, картинка с диска или значок системы."
publish_to: 'none'
version: 1.0.0

resolution: workspace

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  fc_api:
    path: ../api

  fc_ui_api:
    path: ../ui_api

dev_dependencies:
  flutter_test:
    sdk: flutter

  fc_test_kit:
    path: ../test_kit
